/* AI Grow v1 · Local-first prototype. No backend, no fake push. */
(()=>{'use strict';
const STORE='ai-grow-personal-v1';
const $=sel=>document.querySelector(sel);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const offset=(days,base=today())=>{let d=new Date(base+'T12:00:00');d.setDate(d.getDate()+days);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const stamp=(iso)=>{const d=new Date(iso+'T12:00:00');return `${d.getMonth()+1}月${d.getDate()}日`};
const weekStart=()=>{let d=new Date(today()+'T12:00:00');d.setDate(d.getDate()-(d.getDay()+6)%7);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
const uid=()=>Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);
const lesson=(id,title,time,summary,points,prompt,question,choices,answer,why)=>({id,title,time,summary,points,prompt,question,choices,answer,why});
const modules=[
{title:'AI 思维与基础',icon:'🧠',color:'#ecebff',desc:'理解模型如何工作',lessons:[
lesson('l01','让 AI 真正理解你的需求',8,'高质量回答的第一步不是复杂的指令，而是清晰的任务目标。',['把“帮我做”拆成明确的任务、背景和结果。','给出受众、限制与期望格式。','信息不足时，要求 AI 先提出澄清问题。'],'你是一位思路清晰的顾问。我的目标是：[目标]。背景：[背景]。受众：[受众]。请先确认可能缺失的信息，再输出一份可执行方案，格式为 3 个优先级建议。','下面哪种提问最可能获得可执行的回复？',['“介绍一下 AI。”','“面向刚入门的运营，列出 3 个本周可试的 AI 用例，并说明步骤和风险。”','“给我最好的答案。”'],1,'明确目标、对象、数量及交付格式能减少歧义。'),
lesson('l02','判断 AI 回答是否靠谱',9,'模型可以给出流畅但错误的答案。把“验证”加入工作流会更可靠。',['区分事实、推断与建议。','要求可追溯的原始出处，自己核验关键数据。','遇到医疗、法律、投资等高风险内容时尤其谨慎。'],'请把你的回答整理为：已证实事实、合理推断、需要核验的说法。对于后两类标注不确定性和建议核验方式。','AI 给出了一个陌生统计数字，最好的下一步是？',['直接复制发布','要求出处并查验原始数据','让 AI 重复三遍'],1,'语言自信不等于证据可靠。'),
lesson('l03','建立自己的 AI 工作台',7,'不要每天换工具。先让一个主要助手覆盖高频问题，再按需求补足。',['列出你最常做的 3 类任务。','定义输入、AI 处理、人工检查和输出。','用结果是否省时、准确、易复用判断工具价值。'],'我的高频任务是：[任务]。请帮我设计一个 15 分钟以内可以试验的 AI 工作流，包含输入、提示词、检查项、产出。','判断工具是否值得保留的优先标准是？',['功能图标越多越好','真实场景中稳定创造价值','网上讨论量最高'],1,'场景中的稳定收益比功能数量重要。')
]},
{title:'提示词与协作',icon:'✨',color:'#fff0e4',desc:'将想法变成高质量输出',lessons:[
lesson('l04','四段式高效提示词',8,'可以先用「角色—任务—背景—输出」的简单结构。',['角色：界定擅长的专业视角。','任务：描述要完成的具体工作。','背景与限制：说清情境、限制和受众。','输出：规定格式与验收标准。'],'角色：你是一位资深产品经理。\n任务：帮我优化一个 AI 学习 App 的首页。\n背景：用户每天只有 10–20 分钟。\n输出：3 个可执行改进，按优先级排序。','下列哪个元素最能使结果方便直接使用？',['只强调“专业”','指定输出形式和验收标准','反复加感叹号'],1,'输出规格减少二次整理。'),
lesson('l05','迭代提问，而非一次到位',8,'把一次对话当成合作过程：先出草稿，再给定向反馈。',['第一轮：获得初稿与方案假设。','第二轮：指出不符合要求的具体位置。','第三轮：要求修改并对照目标自检。'],'请先给我一版初稿。完成后列出 3 个你最不确定的假设，并问我应该先优化哪一项。','第一版回答不够好，你应该？',['换一个模糊问题','描述哪里不满意并给出修改目标','认为 AI 无法完成'],1,'可操作反馈能显著提高后续输出质量。'),
lesson('l06','让提示词成为可复用模板',10,'优秀的提示词不只是文字，更是可以重复调用的工作方法。',['把每次变化的内容改成 [变量]。','注明适用场景、输入示例、预期输出。','记录迭代后的版本和踩坑点。'],'你是 [角色]。请根据 [输入材料]，面向 [目标受众]，完成 [任务]。限制：[约束]。输出格式：[格式]。完成后按照 [检查标准] 自检。','最值得收藏的是哪一种提示词？',['带有适用条件和可替换变量的模板','一大段没有说明的文本','只有一句“写好一点”'],0,'结构化模板比一次性的句子更方便复用。')
]},
{title:'研究与日常办公',icon:'📚',color:'#e8f4ff',desc:'整理资料、写作与分析',lessons:[
lesson('l07','用 AI 做结构化研究',9,'先构建研究问题，再拆解信息来源和论点。',['列出问题、范围和评价维度。','让 AI 提供研究框架而不是直接相信结论。','优先查看官方文档、论文和原始资料。'],'我要研究 [主题]，目标是 [决策]。请输出研究框架、必须核验的 5 个问题、建议查看的原始来源，以及一个比较表模板。','研究某 AI 产品的最新定价时应优先看？',['随机二手截图','产品官方定价页面','模型猜测'],1,'官方一手资料通常更适合核验变化快的信息。'),
lesson('l08','把会议与笔记变成行动项',8,'用 AI 提取结论和责任人，减少“记下却忘记”的情况。',['整理原始材料并保护隐私。','区分决策、行动、风险和待确认事项。','对截止时间和负责人进行人工核对。'],'请将以下会议记录整理为：一句话结论、已决定事项、行动清单（事项/负责人/截止时间）、未解决问题。没有提及的内容请写“待确认”，不要编造。','会议里没提到责任人时应该？',['自动编一个','标注“待确认”','删掉这件事'],1,'缺失字段应当显式保留，不应凭空填充。')
]},
{title:'图像、视频与多模态',icon:'🎨',color:'#ffebf1',desc:'从文本跨越到视觉表达',lessons:[
lesson('l09','让图像生成更可控',9,'描述清楚主体、场景、构图、色彩、光线和排除项。',['确定视觉风格和用途。','说明主体与画面布局。','针对不满意的局部逐步调整，不必每次重写。'],'请生成一张 [用途] 图片。主体：[主体]。场景：[地点/背景]。构图：[镜头/视角]。光线与色彩：[描述]。风格：[风格]。不希望出现：[排除项]。','哪个描述更可控？',['“帮我做张酷图”','“暖色自然光、俯视桌面、主体居中、留白供标题使用”','“随便做”'],1,'构图和用途等具体约束有助于提高可控性。'),
lesson('l10','从截图中提炼有用信息',8,'图像识别不只是 OCR：还可以让 AI 分类、总结和识别视觉结构。',['先区分提取文字与理解内容两种目标。','对小字号、复杂排版的 OCR 结果进行校对。','保存时加上来源与自己的使用场景。'],'这是我截取的 AI 工具页面。请先提取可读文字，再总结它解决什么问题，列出 3 个值得尝试的场景，并注明你无法确定的部分。','截图里的文字识别完后应该？',['无需检查便直接引用','核对关键字段，补充标签与使用场景','只存图片不整理'],1,'文字识别可能遗漏或误读，关键内容需要复查。')
]},
{title:'自动化与工作流',icon:'⚡',color:'#fff5db',desc:'把重复工作连成系统',lessons:[
lesson('l11','拆解可自动化的工作',10,'从高频、低风险且规则清晰的任务开始。',['画出触发器 → 数据 → 处理 → 输出。','设计人工确认环节和失败重试。','先做最小可运行流程，再逐步增加步骤。'],'请将任务 [任务描述] 拆成：触发条件、输入数据、处理步骤、人工审批点、输出、异常处理。优先给出最小可运行版本。','自动化第一步最适合做什么？',['直接让它代替所有决策','选择高频且规则明确的小任务','一次接入 20 个系统'],1,'先从简单、可验证、可回滚的流程起步。'),
lesson('l12','认识 AI Agent 的边界',9,'Agent 可以规划并调用工具，但仍需要权限管理和运行检查。',['区分聊天、自动化工作流和自主代理。','遵循最小权限原则，敏感操作要确认。','设置停止条件、预算和结果检查。'],'请设计一个用于 [任务] 的 Agent 流程，包含它可以调用的工具、禁止操作、每一步需要的输入、人工审批节点、失败后的回退方式。','Agent 涉及发送邮件或付款时，合适的设计是？',['默认全自动无上限','关键操作先请求人工批准','隐藏操作日志'],1,'不可逆或高风险操作应设置人工审批。')
]},
{title:'AI 产品与搭建',icon:'🚀',color:'#e6f8ed',desc:'从想法到可演示产品',lessons:[
lesson('l13','定义真正值得做的功能',8,'做产品先判断用户问题，不要先堆 AI 功能。',['写清楚目标用户、痛点、完成任务的路径。','列出必须具备的最小功能。','用真实行为验证价值，而不是只问“你喜欢吗”。'],'我有一个 AI 产品想法：[想法]。请帮我写清目标用户、核心问题、单一主流程、最小可用功能和可验证的成功标准。','MVP 第一版优先目标是什么？',['把所有设想都做完','尽快验证最核心的用户价值','先设计很多设置页面'],1,'最小可用版本应围绕一条最重要的用户路径。'),
lesson('l14','把 AI 功能设计成闭环',9,'一次 AI 调用不是产品，输入、输出、反馈和纠错机制同样重要。',['定义用户输入、允许上传的资料和隐私要求。','为生成失败和结果不佳留出补救路径。','提供修改、收藏、继续操作和清晰的状态提示。'],'针对 [AI 功能]，请设计从用户输入到结果交付的交互流程，并补充：加载中、失败、重试、人工修改、隐私提示与成功指标。','AI 功能偶尔出错，产品需要？',['隐藏错误','清晰反馈和可恢复流程','重复提交直到成功但不提醒'],1,'可靠交互比单次“看起来智能”更重要。')
]}
];
const lessonList=modules.flatMap((m,mi)=>m.lessons.map((l,li)=>({...l,module:mi,local:li})));
const tasks=[
{id:'t1',emoji:'✍️',title:'升级一条常用提示词',duration:'约 10 分钟',tag:'提示词',steps:['选一条你最近用过、结果普通的提示词。','补充任务、背景、限制和输出格式。','运行优化前后两个版本，比较差异。'],deliver:'在收藏中保存你的优化后提示词。'},
{id:'t2',emoji:'🔎',title:'验证一条 AI 生成的事实',duration:'约 8 分钟',tag:'信息判断',steps:['找出一条 AI 说出的具体数字或事实。','查找它的原始来源或官方文件。','记录核验结果和不确定性。'],deliver:'写出一句核验结论。'},
{id:'t3',emoji:'📋',title:'让 AI 整理一次资料',duration:'约 12 分钟',tag:'办公效率',steps:['找一份非敏感的笔记或长文。','让 AI 归纳重点和行动项。','人工校对，留下真正有用的结论。'],deliver:'保存你的结构化总结。'},
{id:'t4',emoji:'🎨',title:'生成一张带明确构图的图片',duration:'约 10 分钟',tag:'多模态',steps:['写清楚画面主体、风格和布局。','生成一版，再只修改一个变量。','记录哪个修改改善最多。'],deliver:'收藏最终提示词或图片。'},
{id:'t5',emoji:'🔄',title:'画出一个简单自动化',duration:'约 15 分钟',tag:'工作流',steps:['找一件每周会重复的事情。','写下触发 → 处理 → 输出。','列出一处需要你确认的节点。'],deliver:'保存你的简化工作流。'},
{id:'t6',emoji:'🧪',title:'对比两款 AI 工具',duration:'约 12 分钟',tag:'工具评测',steps:['挑选同一个真实任务。','让两款工具分别完成。','从质量、速度、可复用性评分。'],deliver:'记下哪款更适合这个任务以及原因。'}
];
let stories=[{"id":"openai-gpt6-ui-20261007","category":"大模型","source":"OpenAI · 官方","title":"GPT-6 向更多用户开放，并推出交互式智能界面","summary":"OpenAI 10 月 7 日宣布 GPT-6 在 ChatGPT 中面向更多用户推出，同时引入可交互的视觉界面，帮助用户用图表、控件等方式直接探索问题。","why":"观察 AI 从单纯的聊天窗口走向可操作工具；你可以尝试把学习内容变成互动练习。","url":"https://openai.com/index/gpt-6-for-everyone/","date":"10月7日","publishedAt":"2026-10-07T00:00:00Z","translated":true},{"id":"google-gemini-agent-20261008","category":"Agent","source":"Google Cloud · 官方","title":"Google Cloud 发布面向工作的 Gemini Agent","summary":"Google Cloud 在 10 月 8 日的 Gemini at Work 活动中推出通用工作代理，可利用企业上下文、技能和工具，协助知识工作、内容制作与编码，并提供治理和成本控制。","why":"了解 Agent 如何把工作任务与企业已有工具连接起来；重点观察其权限、成本和审批设计。","url":"https://blog.google/innovation-and-ai/infrastructure-and-cloud/google-cloud/gemini-at-work/","date":"10月8日","publishedAt":"2026-10-08T00:00:00Z","translated":true},{"id":"openai-math-20261006","category":"大模型","source":"OpenAI · 官方","title":"OpenAI 公布 AI 在数学开放问题上的研究进展","summary":"OpenAI 10 月 6 日公开了一批由内部前沿模型产生的数学研究成果，并在 GitHub 分享论文与部分 Lean 形式化证明，强调开放检验与后续同行反馈。","why":"学习如何判断 AI 研究成果的可靠性：是否提供可复核的证明、数据和方法，比标题更重要。","url":"https://openai.com/index/sharing-ai-progress-in-mathematics/","date":"10月6日","publishedAt":"2026-10-06T00:00:00Z","translated":true},{"id":"verge-agents-privacy-20261009","category":"Agent","source":"The Verge · 媒体","title":"消费级 AI Agent 竞争升温，隐私与信任成焦点","summary":"The Verge 10 月 9 日讨论 Meta Muse 与 OpenAI Dots 等 AI Agent 的应用前景，重点关注用户信任、数据权限、商业模式与自动行动的一致性。","why":"在尝试 Agent 工具时，可以先检查它会访问哪些数据、能自动执行哪些操作，以及如何撤销权限。","url":"https://www.theverge.com/podcast/1007408/meta-muse-openai-dots-ai-agent-race-privacy-free","date":"10月9日","publishedAt":"2026-10-09T00:00:00Z","translated":true},{"id":"deepmind-private-memory-20260923","category":"产品","source":"Google DeepMind · 官方","title":"Google DeepMind 探索兼顾隐私的跨设备 AI 记忆","summary":"Google DeepMind 9 月 23 日介绍 Private AI Compute 的服务器端记忆架构，探讨如何在提供跨设备连续体验的同时维持更严格的数据保护。","why":"理解长期记忆类 AI 产品的取舍：方便性、数据保存位置、访问控制和用户可删除性。","url":"https://deepmind.google/blog/advancing-private-ai-compute-with-secure-server-side-memory/","date":"9月23日","publishedAt":"2026-09-23T00:00:00Z","translated":true}];
let newsMeta={generatedAt:'2026-10-09T03:00:00Z',mode:'snapshot',loading:false,error:'',lastFetched:0};
const newsDateLabel=()=>{const t=Date.parse(newsMeta.generatedAt);return Number.isFinite(t)?new Date(t).toLocaleString('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'未知'};
const newsIsOld=()=>Date.now()-Date.parse(newsMeta.generatedAt)>1000*3600*48;
function newsInfo(){const label=newsMeta.mode==='live'?'自动更新简报':'已核验资讯快照';const old=newsIsOld()?' · 可能已过时':'';return `<div class="news-meta"><div><span class="news-live-dot"></span><strong>${label}</strong><small>简报生成于 ${esc(newsDateLabel())}${old} · 每条可查看原文和发布日期</small></div><button class="news-refresh" data-action="refreshNews" ${newsMeta.loading?'disabled':''}>${newsMeta.loading?'更新中…':'↻ 检查更新'}</button></div><div class="news-disclaimer">${newsMeta.mode==='live'?'来自定时采集的公开 RSS；无新资讯时保留最新一批。':'当前为 2026年10月9日核对过来源的初始简报。'} ${newsMeta.error?'此次未取得新数据，继续展示现有内容。':''}系统推送尚未启用，早上 08:30 指的是部署后的采集计划，不等于通知送达。</div>`}
function safeStory(s){if(!s||typeof s!=='object')return null;try{const u=new URL(s.url);if(!['https:','http:'].includes(u.protocol))return null}catch{return null}if(!String(s.title||'').trim())return null;return {id:String(s.id||s.url).slice(0,180),title:String(s.title).slice(0,250),summary:String(s.summary||'请点击原文了解详情。').slice(0,750),why:String(s.why||'阅读原文，思考它将如何影响你的学习或日常工作。').slice(0,420),source:String(s.source||'原始资讯源').slice(0,100),category:['大模型','Agent','生产力','多模态','产品'].includes(s.category)?s.category:'产品',url:s.url,date:String(s.date||'日期未提供').slice(0,40),publishedAt:s.publishedAt,translated:Boolean(s.translated)}}
async function loadNews(manual=false){if(newsMeta.loading)return;if(location.protocol==='file:'){if(manual)toast('本地文件展示已核验快照；部署到 HTTPS 后可检查更新');return}newsMeta.loading=true;newsMeta.error='';if(manual && page==='today')render('today');try{const r=await fetch('./news.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const j=await r.json();if(!Array.isArray(j.items)||!j.items.length)throw new Error('没有可显示的新闻');const valid=j.items.map(safeStory).filter(Boolean);if(!valid.length)throw new Error('资讯内容格式错误');const previous=newsMeta.generatedAt; if(Date.parse(j.generated_at)>=Date.parse(previous)) {stories=valid;newsMeta.generatedAt=j.generated_at;newsMeta.mode=j.source_mode==='verified_snapshot'?'snapshot':'live'}newsMeta.lastFetched=Date.now();if(manual)toast('资讯检查完成'+(newsMeta.generatedAt===previous?'，暂无更新':'，已显示最新简报'));}catch(e){newsMeta.error=e.message;if(manual)toast('暂时无法获取更新，仍可阅读已缓存的真实资讯');}finally{newsMeta.loading=false;if(page==='today')render('today');if($('#modal-root .news-modal-identifier'))newsModal();}}
const seedNote={id:'sample-note',type:'prompt',title:'示例：把想法变成可执行计划',body:'你是一位有经验的执行顾问。请根据我的目标：[目标]，背景：[背景]，限制：[时间 / 资源]，提供 3 步行动方案，并列出第一步能在 15 分钟内完成的事情。',link:'',tags:['提示词','效率','示例'],image:'',created:today(),nextReview:today(),interval:0,reviews:0};
function baseState(){return {notes:[seedNote],doneLessons:{},activity:[],taskHistory:{},xp:0,reminder:'08:30',firstRun:today()}}
let state;try{state={...baseState(),...JSON.parse(localStorage.getItem(STORE)||'{}')}}catch{state=baseState()}
state.notes=Array.isArray(state.notes)?state.notes:[seedNote]; state.doneLessons=state.doneLessons&&typeof state.doneLessons==='object'?state.doneLessons:{};state.activity=Array.isArray(state.activity)?state.activity:[];state.taskHistory=state.taskHistory&&typeof state.taskHistory==='object'?state.taskHistory:{};
let page='today',filter='全部',query='',newsFilter='全部',toastTimer,viewingNote=null,editId=null,uploadedImage='',ocrText='',busyOCR=false,answerSelection=null,quizFeedback=false,quizLessonId=null,reviewReveal=false;
function persist(){try{localStorage.setItem(STORE,JSON.stringify(state));return true}catch(e){toast('保存失败，可能是浏览器存储已满。请先导出备份。');return false}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2800)}
function activity(type){state.activity.push({date:today(),type}); if(state.activity.length>600)state.activity=state.activity.slice(-600)}
function practiced(){return (state.taskHistory[weekStart()]||[])}
function due(){return state.notes.filter(n=>!n.nextReview||n.nextReview<=today())}
function completed(){return Object.keys(state.doneLessons).length}
function nextLesson(){return lessonList.find(l=>!state.doneLessons[l.id])||lessonList[0]}
function daysActive(){return [...new Set(state.activity.map(a=>a.date))]}
function streak(){const d=new Set(daysActive());let day=d.has(today())?today():offset(-1);let n=0;while(d.has(day)){n++;day=offset(-1,day)}return n}
function nav(){const a=[['today','⌂','今日'],['learn','◇','学习'],['notes','▤','收藏'],['growth','✦','成长']];$('#navigation').innerHTML=a.map(([id,icon,name])=>`<button class="nav-btn ${page===id?'active':''}" data-nav="${id}"><span class="nav-icon" style="font-size:25px;line-height:1">${icon}</span><span>${name}</span></button>`).join('')}
function header(title,sub,right=true){return `<div class="page-head"><div><div class="overline">${esc(sub)}</div><h1 class="page-title">${esc(title)}</h1></div>${right?`<div class="head-right"><button class="icon-button" aria-label="设置" data-action="settings">⚙</button><button class="icon-button avatar" aria-label="成长统计" data-nav="growth">✦</button></div>`:''}</div>`}
function heading(label,button='',act=''){return `<div class="heading-row"><strong class="section-heading">${esc(label)}</strong>${button?`<button class="text-button" data-action="${esc(act)}">${esc(button)} ↗</button>`:''}</div>`}
function progress(n,d){return `<div class="progress-track"><div class="progress-fill" style="width:${Math.round(Math.max(0,Math.min(n/d,1))*100)}%"></div></div>`}
const pages={
 today(){const d=new Date(),dayname=['周日','周一','周二','周三','周四','周五','周六'][d.getDay()],l=nextLesson(),w=practiced().length;return `${header('早上好，好奇的你 👋',`${d.getMonth()+1}月${d.getDate()}日 · ${dayname} · 轻松进步的每一天`)}
 <div class="hero"><span class="hero-label">✨ TODAY'S LITTLE WIN</span><div class="hero-title">每天进步一点点，<br>就是很了不起的事。</div><div class="hero-desc">给自己 10–20 分钟，学习一个有用的 AI 技巧。</div><div class="hero-art">🚀</div><button class="hero-cta" data-lesson="${l.id}">继续学习 · ${esc(l.time)} 分钟 →</button></div>
 <div class="today-metrics"><div class="metric"><div class="metric-icon">🔥</div><b>${streak()} <small style="display:inline">天</small></b><small>连续学习</small></div><div class="metric"><div class="metric-icon">⭐</div><b>${state.xp||0}</b><small>成长经验值</small></div><div class="metric"><div class="metric-icon">🌱</div><b>${completed()}/${lessonList.length}</b><small>已学课程</small></div></div>
 ${heading('本周的小目标','查看实践任务','tasks')}<div class="weekly-card"><div class="weekly-top"><strong>💪 自由实践 · 每周任意 3 次</strong><span>${Math.min(3,w)}/3</span></div>${progress(w,3)}<div class="weekly-foot">${w>=3?'本周目标已经达成！好好享受你的成长 🎉':'不要求每天打卡，选自己方便的时间完成即可。'}</div></div>
 ${heading('今日 AI 情报','全部资讯','news')}${newsInfo()}
 ${stories.slice(0,3).map(newsCard).join('')}
 ${heading('值得复习的灵感','去收藏库','notes')}<div class="mini-task" data-action="review"><div class="task-emoji">🧩</div><div class="mini-task-info"><strong>${due().length?`有 ${due().length} 条收藏等待复习`:'今天没有到期的复习'}</strong><span>${due().length?'花 2 分钟让灵感真正记住':'有新灵感也可以随时收藏'}</span></div><span class="arrow-circle">→</span></div>
 ${heading('开始一个小练习','看全部任务','tasks')}${tasks.slice(0,2).map(taskCard).join('')}
 <div class="bottom-spacer"></div>`},
 learn(){let next=nextLesson();return `${header('学习小宇宙 ✨','一个小课程，7–10 分钟轻松搞定')}<div class="learn-banner"><span class="sparkle">🌟</span><strong>知识正在慢慢长大</strong><p>循序渐进地解锁能力，不需要赶进度。今天也从最简单的一步开始。</p>${progress(completed(),lessonList.length)}<span class="banner-stats">已完成 ${completed()}/${lessonList.length} 节 · 下一课「${esc(next.title)}」</span></div>
 ${modules.map((m,mi)=>`<div class="module-head"><div class="module-icon" style="background:${m.color}">${m.icon}</div><div class="module-heading"><strong>第 ${mi+1} 章 · ${esc(m.title)}</strong><small>${esc(m.desc)}</small></div><span class="mod-count">${m.lessons.filter(l=>state.doneLessons[l.id]).length}/${m.lessons.length}</span></div>${m.lessons.map(l=>`<div class="lesson-row ${state.doneLessons[l.id]?'done':''} ${l.id===next.id?'current':''}" data-lesson="${l.id}"><div class="lesson-ring">${state.doneLessons[l.id]?'✓':'✦'}</div><div class="lesson-info"><strong>${esc(l.title)}</strong><small>📖 ${l.time} 分钟 · 1 道趣味小测</small></div><span class="lesson-go">→</span></div>`).join('')}`).join('')}<div class="bottom-spacer"></div>`},
 notes(){const tags=['全部','提示词','工具','文章','效率','学习','灵感'];let a=state.notes.filter(n=>(filter==='全部'||(n.tags||[]).includes(filter)||n.type===filter)&&(!query||[n.title,n.body,(n.tags||[]).join(' '),n.link].join(' ').toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.created.localeCompare(a.created));return `${header('灵感收藏盒 📦',`已收藏 ${state.notes.length} 条 · 到期待复习 ${due().length} 条`)}<div class="review-banner"><span style="font-size:27px">🧠</span><div><strong>让好点子记得更牢</strong><small>${due().length} 条到期 · 间隔复习，不用死记硬背</small></div><button data-action="review">去复习 →</button></div><div class="search-box"><span>⌕</span><input id="note-search" placeholder="搜索标题、内容或标签" value="${esc(query)}" autocomplete="off"></div><div class="filters">${tags.map(t=>`<button class="chip ${t===filter?'active':''}" data-filter="${t}">${t}</button>`).join('')}</div><div id="note-results">${a.length?a.map(noteCard).join(''):'<div class="empty"><span class="empty-emoji">🔎</span>暂时没有匹配的收藏。<br>试试其他关键词或新建一条。</div>'}</div><button class="floating-add" data-action="addNote">＋ 保存新灵感</button><div class="bottom-spacer"></div>`},
 growth(){let uniqueDays=daysActive(),w=practiced().length;const week=['一','二','三','四','五','六','日'];const start=weekStart();return `${header('成长看得见 🌱','慢慢来，你已经走在路上')}<div class="growth-hero"><div><small>YOUR AI GROWTH JOURNEY</small><strong>${state.xp||0} XP</strong><small>知识一点点，能力越来越强</small></div><span class="growth-art">🏆</span></div>
 ${heading('我的成长数据')}<div class="stat-grid"><div class="stat-tile"><span class="emoji">📘</span><strong>${completed()}</strong><span>完成课程</span></div><div class="stat-tile"><span class="emoji">🔥</span><strong>${streak()}</strong><span>连续活跃天数</span></div><div class="stat-tile"><span class="emoji">💼</span><strong>${w}/3</strong><span>本周自由实践</span></div><div class="stat-tile"><span class="emoji">📌</span><strong>${state.notes.length}</strong><span>个人收藏</span></div></div>
 ${heading('本周足迹')}<div class="history">${week.map((x,i)=>{let date=offset(i,start),active=uniqueDays.includes(date);return `<div style="text-align:center"><div style="font-size:10px;color:#989bb0;margin-bottom:6px">${x}</div><div class="day-dot ${active?'active':''} ${date===today()?'today':''}">${active?'✓':parseInt(date.slice(-2))}</div></div>`}).join('')}</div><div class="weekly-card"><div class="weekly-top"><strong>✨ 本周实践目标</strong><span>${Math.min(w,3)}/3</span></div>${progress(w,3)}<div class="weekly-foot">自由安排，每周完成 3 个实践就够了。</div><button class="text-button" data-action="tasks">看看本周任务 →</button></div>
 ${heading('AI 能力地图')}<div class="soft-card">${modules.map((m,i)=>{let count=m.lessons.filter(l=>state.doneLessons[l.id]).length;return `<div class="skill-row"><div class="skill-title"><span>${m.icon} ${esc(m.title)}</span><span>${Math.round(count/m.lessons.length*100)}%</span></div>${progress(count,m.lessons.length)}</div>`}).join('')}<div class="field-help">进度来自真实完成的课程，不会因几天没学而清零。</div></div>
 ${heading('小小里程碑')}<div>${[['🌟','学习启程','完成第一节课',completed()>=1],['🧠','知识积累家','完成 5 节课',completed()>=5],['🏃','实践行动派','任意一周完成 3 次实践',Object.values(state.taskHistory).some(x=>x.length>=3)],['📌','灵感收藏家','保存至少 3 条笔记',state.notes.length>=3]].map(([ico,title,sub,ok])=>`<div class="achievement"><span class="badge-art">${ico}</span><div><strong>${title}</strong><small>${sub}</small></div><span class="status">${ok?'已解锁 ✓':'待解锁'}</span></div>`).join('')}</div><div class="bottom-spacer"></div>`}
};
function newsCard(s){return `<article class="news-card"><div class="news-head"><span class="news-source">${esc(s.source)}</span><span>· ${esc(s.date)}</span><span class="pill">${esc(s.category)}</span></div><h3 class="news-title">${esc(s.title)}</h3><p class="news-summary">${esc(s.summary)}</p>${s.translated?'':'<div class="field-help" style="margin-bottom:12px">原文自动抓取 · 暂无中文 AI 摘要（请配置密钥）</div>'}<div class="news-bottom"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">阅读原文 ↗</a><button class="learn-why" data-action="newsWhy" data-idx="${stories.indexOf(s)}">为什么值得关注？</button></div></article>`}
function taskCard(t){let ok=practiced().includes(t.id);return `<div class="mini-task" data-task="${t.id}"><div class="task-emoji">${t.emoji}</div><div class="mini-task-info"><strong>${esc(t.title)} ${ok?'✅':''}</strong><span>${esc(t.duration)} · ${esc(t.tag)}</span></div><span class="arrow-circle">${ok?'✓':'→'}</span></div>`}
function noteCard(n){let types={prompt:'✨ 提示词',tool:'🧰 AI 工具',article:'📚 文章 / 资讯',note:'💡 灵感笔记'};return `<article class="note-card"><div class="note-top"><span class="note-type">${types[n.type]||types.note}</span><span class="note-date">${esc(stamp(n.created||today()))}</span></div><h3 class="note-title">${esc(n.title)}</h3><div class="note-body">${esc(n.body||n.link||'（仅图片）')}</div>${n.image&&n.image.startsWith('data:image/')?`<img class="note-image" alt="收藏截图" src="${n.image}">`:''}<div class="tag-line">${(n.tags||[]).map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}${n.nextReview<=today()?'<span class="tag" style="color:#c5845e;background:#fff3e8">待复习</span>':''}</div><div class="note-actions"><button data-noteview="${esc(n.id)}">📖 查看</button><button data-noteedit="${esc(n.id)}">✎ 编辑</button>${n.link?`<button data-noteopen="${esc(n.id)}">↗ 来源</button>`:''}<button class="danger" data-notedelete="${esc(n.id)}">删除</button></div></article>`}
function render(p=page){page=p;nav();$('#screen').innerHTML=pages[page]();$('#screen').scrollTop=0}
function modal(title,content){$('#modal-root').innerHTML=`<div class="modal-cover" data-dismiss="1"><section class="modal" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-bar"></div><div class="modal-head"><h2>${esc(title)}</h2><button class="modal-close" data-action="closeModal" aria-label="关闭">✕</button></div><div class="modal-content">${content}</div></section></div>`;$('.modal-cover').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()})}
function closeModal(){ $('#modal-root').innerHTML='';uploadedImage='';ocrText='';busyOCR=false;editId=null;quizLessonId=null;answerSelection=null;quizFeedback=false;reviewReveal=false}
function openLesson(id){let l=lessonList.find(x=>x.id===id);if(!l)return;quizLessonId=l.id;answerSelection=null;quizFeedback=false;modal('今日小课堂',lessonContent(l))}
function lessonContent(l){const done=Boolean(state.doneLessons[l.id]);return `<div class="lesson-intro"><span>第 ${l.module+1} 章 · ${l.time} 分钟 · ${done?'已完成 ✓':'互动学习'}</span><strong>${esc(l.title)}</strong><p>${esc(l.summary)}</p></div><div class="content-heading">今天记住这几点</div><ul class="bullet-list">${l.points.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="content-heading">可直接套用的小模板</div><div class="prompt-box" id="lesson-prompt">${esc(l.prompt)}</div><button class="text-button" data-action="copyPrompt">📋 复制提示词</button><div class="quiz" id="quiz"><div class="quiz-title">🧩 试试看 · ${esc(l.question)}</div>${l.choices.map((x,i)=>`<button class="option ${answerSelection===i?'selected':''} ${quizFeedback?(i===l.answer?'correct':answerSelection===i?'wrong':''):''}" data-answer="${i}"><span class="circle">${quizFeedback&&i===l.answer?'✓':String.fromCharCode(65+i)}</span>${esc(x)}</button>`).join('')}${quizFeedback?`<div class="feedback ${answerSelection!==l.answer?'warn':''}">${answerSelection===l.answer?'🎉 回答正确！':'再想一想～'} ${esc(l.why)}</div>`:''}</div><div class="btn-row"><button class="secondary-button" data-action="saveLesson">收藏模板</button><button class="primary-button" data-action="finishLesson" ${!quizFeedback?'disabled style="opacity:.5;cursor:not-allowed"':''}>${done?'再学一次 ✓':'完成这节课 · +20 XP'}</button></div>`}
function answer(i){let l=lessonList.find(x=>x.id===quizLessonId);if(!l)return;answerSelection=i;quizFeedback=true;const content=lessonContent(l);$('.modal-content').innerHTML=content;const quiz=$('#quiz');if(quiz)quiz.scrollIntoView({block:'nearest',behavior:'smooth'})}
function finishLesson(){if(!quizFeedback)return toast('先完成这道小测验。');let l=lessonList.find(x=>x.id===quizLessonId);if(!l)return;if(!state.doneLessons[l.id]){state.doneLessons[l.id]=today();state.xp=(state.xp||0)+20;activity('lesson');persist();toast('🎉 又完成一课！+20 XP')}else toast('复习得不错！');closeModal();render('learn')}
function saveLesson(){const l=lessonList.find(x=>x.id===quizLessonId);if(!l)return;state.notes.unshift({id:uid(),type:'prompt',title:'课程模板：'+l.title,body:l.prompt,link:'',tags:['提示词','学习'],image:'',created:today(),nextReview:offset(1),interval:1,reviews:0});persist();toast('已加入收藏，明天可复习')}
function tasksModal(){const done=practiced();modal('本周自由实践',`<div class="hint-box">一周只要完成 <b>3 个不同的小实践</b> 就达标，可自由选择顺序和日期。每个任务只在本周计一次。${done.length>=3?' 🎉 本周已达标！':''}</div><div class="weekly-card" style="margin-bottom:14px"><div class="weekly-top"><strong>本周实践进度</strong><span>${Math.min(done.length,3)}/3</span></div>${progress(done.length,3)}</div>${tasks.map(t=>taskCard(t)).join('')}`)}
function openTask(id){let t=tasks.find(x=>x.id===id);if(!t)return;const already=practiced().includes(id);modal('每周 AI 实践',`<div class="lesson-intro"><span>${esc(t.duration)} · ${esc(t.tag)}</span><strong>${t.emoji} ${esc(t.title)}</strong><p>不必上传作业；认真完成后自己点击标记即可。</p></div><div class="content-heading">动手试一试</div>${t.steps.map((s,i)=>`<div class="task-step"><strong>${i+1}. </strong>${esc(s)}</div>`).join('')}<div class="hint-box"><b>完成标准：</b>${esc(t.deliver)}</div><div class="btn-row"><button class="secondary-button" data-action="addNote">把成果记下来</button><button class="primary-button" data-finish-task="${t.id}" ${already?'disabled style="opacity:.55"':''}>${already?'本周已完成 ✓':'我已完成 · +30 XP'}</button></div>`)}
function finishTask(id){let l=state.taskHistory[weekStart()]||[];if(l.includes(id))return toast('本周已完成这个任务');l.push(id);state.taskHistory[weekStart()]=l;state.xp=(state.xp||0)+30;activity('practice');persist();toast(l.length===3?'🎉 本周 3 次实践达标！':'太好了，实践完成！+30 XP');closeModal();render('today')}
function newsModal(){modal('全球 AI 资讯 · 中文精选',`<div class="news-modal-identifier">${newsInfo()}</div><div class="filters" style="padding-left:0;margin-left:0">${['全部','大模型','Agent','生产力','多模态','产品'].map(t=>`<button class="chip ${newsFilter===t?'active':''}" data-newsfilter="${t}">${t}</button>`).join('')}</div><div id="news-results">${stories.filter(s=>newsFilter==='全部'||s.category===newsFilter).map(newsCard).join('')||'<div class="empty">暂无此类别资讯，试试其他主题。</div>'}</div><div class="source-list"><a class="source-link" href="https://openai.com/news/" target="_blank" rel="noopener noreferrer">OpenAI News<span>官方 ↗</span></a><a class="source-link" href="https://deepmind.google/blog/" target="_blank" rel="noopener noreferrer">Google DeepMind<span>官方 ↗</span></a><a class="source-link" href="https://blog.google/innovation-and-ai/technology/ai/" target="_blank" rel="noopener noreferrer">Google AI<span>官方 ↗</span></a><a class="source-link" href="https://huggingface.co/blog" target="_blank" rel="noopener noreferrer">Hugging Face<span>官方 ↗</span></a></div>`)}
function newsWhy(i){let n=stories[i];if(!n)return;modal('为什么值得关注？',`<div class="lesson-intro"><span>${esc(n.category)} · 趋势解读</span><strong>${esc(n.title)}</strong><p>${esc(n.summary)}</p></div><div class="content-heading">对你的学习有什么帮助？</div><div class="hint-box">💡 ${esc(n.why)}</div><div class="btn-row"><button class="secondary-button" data-action="saveNews" data-idx="${i}">收藏这条趋势</button><a class="primary-button" href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">查看相关资料 ↗</a></div>`)}
function saveNews(i){const n=stories[i];if(!n)return;state.notes.unshift({id:uid(),type:'article',title:n.title,body:n.summary+'\n学习角度：'+n.why,link:n.url,tags:['文章',n.category],image:'',created:today(),nextReview:offset(1),interval:1,reviews:0});persist();toast('已保存，明天推荐复习')}
function noteForm(n){const ex=Boolean(n);editId=n?.id||null;uploadedImage=n?.image||'';ocrText='';let tags=n?.tags?.join(', ')||'';modal(ex?'编辑收藏':'保存一个好点子',`<form id="note-form"><label class="label">类型</label><select class="field" name="type"><option value="prompt" ${n?.type==='prompt'?'selected':''}>✨ 提示词</option><option value="tool" ${n?.type==='tool'?'selected':''}>🧰 AI 工具</option><option value="article" ${n?.type==='article'?'selected':''}>📚 文章 / 资讯</option><option value="note" ${n?.type==='note'?'selected':''}>💡 灵感笔记</option></select><label class="label">标题 *</label><input class="field" name="title" maxlength="90" required placeholder="例如：适合做报告的结构化提示词" value="${esc(n?.title||'')}"><label class="label">正文 / 提示词 / 个人心得</label><textarea class="field textarea" id="note-body-field" name="body" placeholder="直接粘贴你看到的文字，或者写下自己的想法…">${esc(n?.body||'')}</textarea><label class="label">原始链接（可选）</label><input class="field" name="link" type="url" placeholder="https://..." value="${esc(n?.link||'')}"><label class="label">标签（使用逗号分隔）</label><input class="field" name="tags" placeholder="例如：提示词, 办公, 写作" value="${esc(tags)}"><label class="label">添加截图并尝试文字识别</label><input type="file" id="note-image-input" accept="image/*" style="display:none"><div class="image-tools"><button class="secondary-button" type="button" data-action="uploadImage">📷 上传截图</button><button class="secondary-button" type="button" data-action="ocrImage" ${uploadedImage?'':'disabled'} id="ocr-button">🔎 识别图片文字</button>${uploadedImage?'<button class="text-button" type="button" data-action="removeImage">移除图片</button>':''}</div><div id="image-container">${uploadedImage?`<img class="image-preview" src="${uploadedImage}" alt="图片预览">`:''}</div><div id="ocr-status" class="field-help">OCR 需要联网加载识别组件，文字可能有误，保存前请核对。图片只在本机处理，不会发送给 AI Grow 服务器。</div><div class="hint-box">🔐 第一版笔记、图片和学习数据保存在当前浏览器中。建议定期在「设置」里导出备份；清除浏览器数据可能导致丢失。</div><button type="submit" class="primary-button">${ex?'保存修改':'💜 收进我的收藏盒'}</button></form>`)}
async function fileImage(file){if(!file||!file.type.startsWith('image/'))return toast('请选择图片文件');if(file.size>15*1024*1024)return toast('图片太大，请选择 15MB 以内的图片');try{const original=await new Promise((resolve,reject)=>{let r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file)});const img=new Image();img.src=original;await img.decode();let scale=Math.min(1,1000/Math.max(img.width,img.height));let c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d').drawImage(img,0,0,c.width,c.height);uploadedImage=c.toDataURL('image/jpeg',.67);$('#image-container').innerHTML=`<img class="image-preview" alt="截图预览" src="${uploadedImage}">`;$('#ocr-button').disabled=false;toast('截图已添加，可尝试识别文字')}catch(e){console.error(e);toast('图片载入失败，请换一张试试')}}
async function ocrImage(){if(!uploadedImage)return toast('请先上传图片');if(busyOCR)return;busyOCR=true;const btn=$('#ocr-button'),status=$('#ocr-status');btn.disabled=true;status.textContent='正在准备识别组件（需连接网络）…';try{if(!window.Tesseract){await new Promise((res,rej)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js';s.onload=res;s.onerror=()=>rej(new Error('OCR 组件加载失败'));document.head.appendChild(s)})}status.textContent='正在提取图片文字，请不要关闭页面…';const r=await window.Tesseract.recognize(uploadedImage,'chi_sim+eng');ocrText=(r.data.text||'').trim();if(!ocrText){status.textContent='没有识别到可用文字，请尝试更清晰的截图。';return}const t=$('#note-body-field');t.value=[t.value.trim(),ocrText].filter(Boolean).join('\n\n—— 截图识别 ——\n');status.textContent=`已提取 ${ocrText.length} 个字符并添加到正文。请核对错别字。`;toast('✨ 已把识别结果加入正文')}catch(e){console.warn(e);status.textContent='识别暂时不可用：请确认网络连接，或手动粘贴图片中的文字。';toast('OCR 组件不可用，仍可保存截图')}finally{busyOCR=false;if(btn)btn.disabled=false}}
function saveNote(form){const f=new FormData(form),title=String(f.get('title')||'').trim(),body=String(f.get('body')||'').trim(),link=String(f.get('link')||'').trim();if(!title)return toast('请写一个标题');if(link){try{let u=new URL(link);if(!['https:','http:'].includes(u.protocol))throw new Error()}catch{return toast('来源链接需要以 http:// 或 https:// 开头')}}let tags=[...new Set(String(f.get('tags')||'').split(/[,，、\n]/).map(x=>x.trim().replace(/^#/,'')).filter(Boolean))].slice(0,12);const prior=state.notes.find(n=>n.id===editId);let n={id:editId||uid(),type:f.get('type')||'note',title,body,link,tags,image:uploadedImage,created:prior?.created||today(),nextReview:prior?.nextReview||offset(1),interval:prior?.interval||1,reviews:prior?.reviews||0};if(editId){state.notes=state.notes.map(x=>x.id===editId?n:x)}else state.notes.unshift(n);if(!persist())return;closeModal();render('notes');toast(editId?'保存修改成功':'💜 已保存到收藏盒')}
function seeNote(id){let n=state.notes.find(n=>n.id===id);if(!n)return;viewingNote=n.id;modal(n.title,`<div class="note-top"><span class="note-type">${n.type==='prompt'?'✨ 提示词':n.type==='tool'?'🧰 AI 工具':n.type==='article'?'📚 文章':'💡 笔记'}</span><span class="note-date">${esc(stamp(n.created))}</span></div><div class="review-front" style="max-height:300px;margin-top:14px">${esc(n.body||'无文字内容')}</div>${n.image?`<img src="${n.image}" alt="保存的图片" style="max-width:100%;max-height:280px;border-radius:12px;margin-top:13px">`:''}<div class="tag-line">${n.tags.map(t=>`<span class="tag">#${esc(t)}</span>`).join('')}</div>${n.link?`<a href="${esc(n.link)}" rel="noopener noreferrer" target="_blank" class="text-button">🔗 打开原始链接 ↗</a>`:''}<div class="hint-box">📅 下次复习：${esc(stamp(n.nextReview||today()))} · 已复习 ${n.reviews||0} 次</div><div class="btn-row"><button class="secondary-button" data-noteedit="${esc(n.id)}">编辑</button><button class="primary-button" data-action="review">复习收藏内容</button></div>`)}
function reviewModal(){const n=due()[0];if(!n){modal('复习完成 🎉',`<div class="empty"><span class="empty-emoji">🌿</span>今天已经没有到期的笔记了。<br>好点子会在合适的时间再次出现。</div><button class="primary-button" data-action="closeModal">太棒了</button>`);return}viewingNote=n.id;reviewReveal=false;drawReview()}
function drawReview(){const n=state.notes.find(n=>n.id===viewingNote);if(!n)return reviewModal();modal('2 分钟知识复习',`<div class="overline">待复习 ${due().length} 条 · 空闲时再做也没关系</div><div class="lesson-intro" style="margin-top:10px"><span>🧠 回忆练习</span><strong>${esc(n.title)}</strong><p>先回想：这条收藏能解决什么问题？有什么具体用法？</p></div>${reviewReveal?`<div class="content-heading">看看你以前记下的内容</div><div class="review-front">${esc(n.body||n.link||'图片笔记') }</div>${n.image?`<img class="note-image" src="${n.image}" alt="收藏截图">`:''}<div class="btn-row"><button class="secondary-button" data-review-grade="again">还不熟悉 · 明天再看</button><button class="primary-button" data-review-grade="remember">记住了 ✓</button></div>`:'<button class="primary-button" data-action="revealReview">👀 点击查看内容</button>'}`)}
function gradeReview(which){const n=state.notes.find(n=>n.id===viewingNote);if(!n)return;let interval=which==='again'?1:(n.interval>=7?Math.min(n.interval*2,60):[1,3,7,14][Math.min(n.reviews||0,3)]);n.interval=interval;n.reviews=(n.reviews||0)+1;n.nextReview=offset(interval);activity('review');persist();toast(which==='again'?'已安排明天再复习':'✨ 复习完成，知识更牢了');reviewModal();render(page)}
function settings(){modal('偏好设置',`<div class="setting-row"><div><strong>⏰ 每日 AI 资讯提醒</strong><small>你确认的早上推送时间</small></div><span class="setting-value">${esc(state.reminder)}</span></div><div class="setting-row"><div><strong>🔔 系统推送状态</strong><small>已支持部署后定时抓取资讯；系统推送通知尚未启用</small></div><span class="setting-value">未启用</span></div><div class="setting-row"><div><strong>💾 数据保存位置</strong><small>本机浏览器 localStorage；未启用云端同步</small></div><span class="setting-value">本机</span></div><div class="setting-row"><div><strong>📷 截图文字提取</strong><small>需要网络访问第三方 OCR 组件。图片在浏览器处理</small></div><span class="setting-value">可试用</span></div><div class="small-subheading">管理学习资料</div><div class="export-row"><button class="secondary-button" data-action="exportData">↓ 导出全部资料</button><button class="secondary-button" data-action="importData">↑ 导入备份</button></div><input type="file" accept=".json,application/json" id="import-file" hidden><div class="hint-box">💡 在 iPhone Safari 中，把部署后的站点添加到主屏幕可获得更接近 App 的使用体验。部署后可按早上 08:30 自动采集资讯并在打开 App 时加载；真正的系统消息推送尚未包含在 V1.1。</div><button class="text-button" style="color:#bb7575" data-action="resetData">重置所有测试数据</button>`)}
function exportData(){const blob=new Blob([JSON.stringify({version:1,exported:new Date().toISOString(),data:state},null,2)],{type:'application/json'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='AI-Grow-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000);toast('备份下载已准备')}
async function importData(file){if(!file)return;try{const raw=JSON.parse(await file.text());const dat=raw.data||raw;if(!Array.isArray(dat.notes)||!dat.doneLessons||!Array.isArray(dat.activity))throw new Error('结构不匹配');if(!confirm('导入会覆盖当前设备上的收藏和学习记录，确认继续吗？'))return;state={...baseState(),...dat};persist();closeModal();render('today');toast('备份导入成功')}catch(e){toast('无法读取此备份，请选择 AI Grow 导出的 JSON 文件')}}
function removeNote(id){let n=state.notes.find(n=>n.id===id);if(!n)return;if(!confirm('确定删除「'+n.title+'」吗？删除后无法恢复。'))return;state.notes=state.notes.filter(n=>n.id!==id);persist();if($('#modal-root').innerHTML)closeModal();render('notes');toast('已删除这条收藏')}
function action(a,element){switch(a){case'settings':settings();break;case'closeModal':closeModal();break;case'addNote':noteForm(null);break;case'uploadImage':$('#note-image-input')?.click();break;case'ocrImage':ocrImage();break;case'removeImage':uploadedImage='';$('#image-container').innerHTML='';$('#ocr-button').disabled=true;break;case'tasks':tasksModal();break;case'news':newsModal();break;case'refreshNews':loadNews(true);break;case'newsWhy':newsWhy(+element.dataset.idx);break;case'saveNews':saveNews(+element.dataset.idx);break;case'copyPrompt':{const l=lessonList.find(x=>x.id===quizLessonId);if(l)copyText(l.prompt);break}case'finishLesson':finishLesson();break;case'saveLesson':saveLesson();break;case'review':reviewModal();break;case'revealReview':reviewReveal=true;drawReview();break;case'exportData':exportData();break;case'importData':$('#import-file')?.click();break;case'resetData':if(confirm('这会删除所有笔记、实践与学习进度。建议先导出备份。确定重置吗？')){state=baseState();persist();closeModal();render('today');toast('测试数据已重置')}break;}}
async function copyText(str){try{await navigator.clipboard.writeText(str);toast('已复制到剪贴板')}catch{let t=document.createElement('textarea');t.value=str;document.body.appendChild(t);t.select();try{document.execCommand('copy');toast('已复制模板')}catch{toast('复制失败，请手动选择文字')}t.remove()}}
document.addEventListener('click',e=>{const el=e.target.closest('[data-nav],[data-action],[data-lesson],[data-task],[data-answer],[data-finish-task],[data-filter],[data-newsfilter],[data-noteview],[data-noteedit],[data-notedelete],[data-noteopen],[data-review-grade]');if(!el||el.disabled)return;
if(el.dataset.nav){closeModal();render(el.dataset.nav);return}if(el.dataset.action){action(el.dataset.action,el);return}if(el.dataset.lesson){openLesson(el.dataset.lesson);return}if(el.dataset.task){openTask(el.dataset.task);return}if(el.dataset.answer!==undefined){answer(+el.dataset.answer);return}if(el.dataset.finishTask){finishTask(el.dataset.finishTask);return}
if(el.dataset.filter){filter=el.dataset.filter;const sr=$('#note-search');const start=sr?.selectionStart||0;render('notes');$('#note-search')?.focus();$('#note-search')?.setSelectionRange(start,start);return}if(el.dataset.newsfilter){newsFilter=el.dataset.newsfilter;newsModal();return}
if(el.dataset.noteview){seeNote(el.dataset.noteview);return}if(el.dataset.noteedit){noteForm(state.notes.find(n=>n.id===el.dataset.noteedit));return}if(el.dataset.notedelete){removeNote(el.dataset.notedelete);return}if(el.dataset.noteopen){let n=state.notes.find(n=>n.id===el.dataset.noteopen);if(n?.link)window.open(n.link,'_blank','noopener');return}if(el.dataset.reviewGrade){gradeReview(el.dataset.reviewGrade);return}});
document.addEventListener('submit',e=>{if(e.target.id==='note-form'){e.preventDefault();saveNote(e.target)}});
document.addEventListener('input',e=>{if(e.target.id==='note-search'){query=e.target.value;let a=state.notes.filter(n=>(filter==='全部'||(n.tags||[]).includes(filter)||n.type===filter)&&[n.title,n.body,(n.tags||[]).join(' '),n.link].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.created.localeCompare(a.created));$('#note-results').innerHTML=a.length?a.map(noteCard).join(''):'<div class="empty">没有找到匹配的收藏</div>'}});
document.addEventListener('change',e=>{if(e.target.id==='note-image-input')fileImage(e.target.files?.[0]);if(e.target.id==='import-file')importData(e.target.files?.[0])});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
const time=$('#local-time');function clock(){time.textContent=new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}clock();setInterval(clock,60*1000);render();loadNews();document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Date.now()-newsMeta.lastFetched>1000*3600*3)loadNews()});
if('serviceWorker'in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
